---
job:
    env_set:
        # In case wandb process interferes with
        # hydra's multi-launcher
        WANDB_START_METHOD: thread
launcher:
    ray:
        remote:
            num_gpus: 2
            num_cpus: 16
